print("Lab-08")
print("Hassan Ahmed Inamdar 18B-080-CS, Sec-A")
print("Question 5(a)")
message = 'The secret of this message is that it is secret.'
print(message)
print("Question 5(b)")
length = len(message)
print(length)
print("Question 5(c)")
count = message.count('secret')
print(count)
print("Question 5(d)")
censored = message.replace('secret','xxxxxx')
print(censored)
