print("Lab-08 ")
print("Hassan Ahmed Inamdar 18B-080-CS, Sec - A")
print("Question 2(a)")
forecast = ("It will be a sunny day today.")
count = forecast.count("day")
print(count)
print("Question 2(b)")
weather = forecast.find("sunny")
print(weather)
print("Question 2(c)")
change = forecast.replace("sunny","cloudy")
print(change)
